[package]
name       = "eip-2539-test-gen"
authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
repository = { workspace = true }
version    = { workspace = true }

[dependencies]
